config/routes.rb
LauncherJournal::Application.routes.draw do
  root to: 'entries#index'

  resources :entries
  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false

  has_many :entries, inverse_of: :category
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates_presence_of :title
  validates_presence_of :description
  validates_presence_of :user_id

  belongs_to :category, inverse_of: :entries
  belongs_to :user, inverse_of: :entries

  def category_name
    if category.nil?
      ""
    else
      category.name
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :first_name, :last_name

  has_many :entries

  def full_name
    @full_name = "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  respond_to :html # what does this do?

  # GET /categories
  def index
    @categories = Category.all.order('name ASC')
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1
  def show
    @category = Category.find(params[:id])
  end

  # POST /articles
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to :categories
    else
      render action: 'new'
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  #PUT/PATCH /categories/1
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  #DELETE /categories/1
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  respond_to :html # what does this do?

  # GET /entries
  def index
    @entries = Entry.all.order('created_at DESC')
  end

  #GET /entries/1
  def show
    @entry = Entry.find(params[:id])
  end

  #GET /entries/new
  def new
    @entry = Entry.new
  end

  #POST /entries
  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to entries_path
    else
      render 'new'
    end
  end

  #GET /entries/1/edit
  def edit
    @entry = Entry.find(params[:id])
  end

  #POST /entries/1
  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_params)
      redirect_to entry_path(@entry)
    else
      render 'edit'
    end
  end

  #DELETE /entries/1
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entries_path
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :user_id, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited
      this category from being saved:</h2>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit 'Submit'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div>
  <h1>Edit Category</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <li><%= link_to 'New Category', new_category_path %></li>
  <li><%= link_to 'Entries', entries_path %></li>
</ul>

<h3>List of all categories (sorted by name)</h3>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category_path(category) %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<div>
  <h1>Create New Category</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>Category</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <tr>
    <td><%= @category.name %></td>
    <td><%= link_to 'Edit', edit_category_path(@category) %></td>
    <td><%= link_to 'Destroy', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
</table>

<%= link_to 'Back', categories_path %>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>

  <% if @entry.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@entry.errors.count, "error") %> prohibited
      this entry from being saved:</h2>
    <ul>
    <% @entry.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div>
    <%= f.label :user %>
    <%= f.collection_select(:user_id, User.all, :id, :full_name) %>
  </div>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, include_blank: true) %>
  </div>

  <div>
    <%= f.submit 'Submit'%>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div>
  <h1>Edit Entry</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Entries</h1>

<ul>
  <li><%= link_to 'New Entry', new_entry_path %></li>
  <li><%= link_to 'Categories', categories_path %></li>
</ul>

<h3>List of all entries by all users (sorted by date created, descending)</h3>

<table>
  <tr>
    <th>Date Created</th>
    <th>User</th>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
  </tr>
  <% @entries.each do |entry| %>
  <tr>
    <td><%= entry.created_at %></td>
    <td><%= "#{entry.user.first_name} #{entry.user.last_name}" %></td>
    <td><%= entry.title %></td>
    <td><%= entry.description %></td>
    <td><%= entry.category_name %></td>
    <td><%= link_to 'Show', entry_path(entry) %></td>
    <td><%= link_to 'Edit', edit_entry_path(entry) %></td>

    <!-- Cut and pasted the below from rails guide tutorial.  Necessary to specify method? -->
    <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>

</table>

app/views/entries/new.html.erb
<div>
  <h1>Create New Entry</h1>
</div>

<%= render 'form' %>

app/views/entries/show.html.erb
<h1>Entry Number <%= "#{params[:id]}"%> </h1>

<table>
  <tr>
    <th>Date Created</th>
    <th>User</th>
    <th>Title</th>
    <th>Description</th>
    <th>Category</th>
  </tr>

  <tr>
    <td><%= @entry.created_at %></td>
    <td><%= "#{@entry.user.first_name} #{@entry.user.last_name}" %></td>
    <td><%= @entry.title %></td>
    <td><%= @entry.description %></td>
    <td><%= @entry.category_name %></td>
    <td><%= link_to 'Edit', edit_entry_path(@entry) %></td>
    <td><%= link_to 'Destroy', entry_path(@entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

</table>
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LauncherJournal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>